# Generated by Django 4.2.8 on 2026-01-19 09:58

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('PISO', 'Piso'), ('LOCAL', 'Local Comercial'), ('CASA', 'Casa'), ('GARAJE', 'Garaje')], default='PISO', max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('referencias_catastro', models.CharField(blank=True, max_length=255, null=True)),
                ('renta_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5)),
                ('irpf_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5)),
                ('fecha_inicio_alquiler', models.DateField()),
                ('fecha_fin_alquiler', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Inmuebles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('mes', models.DateField()),
                ('es_bruto', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='app.inmueble')),
            ],
            options={
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_participacion', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Socios',
                'ordering': ['usuario__first_name'],
            },
        ),
        migrations.AddField(
            model_name='inmueble',
            name='socios',
            field=models.ManyToManyField(blank=True, related_name='inmuebles', to='app.socio'),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento'), ('REPARACION', 'Reparación'), ('SERVICIOS', 'Servicios (agua, luz, gas)'), ('SEGUROS', 'Seguros'), ('ADMINISTRATIVO', 'Gastos Administrativos'), ('OTRO', 'Otro')], max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('factura_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='app.inmueble')),
            ],
            options={
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DeclaracionTrimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('trimestre', models.CharField(choices=[('Q1', 'Q1 (Enero-Marzo)'), ('Q2', 'Q2 (Abril-Junio)'), ('Q3', 'Q3 (Julio-Septiembre)'), ('Q4', 'Q4 (Octubre-Diciembre)')], max_length=2)),
                ('iva_total_ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva_total_gasto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva_a_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('irpf_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('declarado', models.BooleanField(default=False)),
                ('fecha_declaracion', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaraciones', to='app.socio')),
            ],
            options={
                'verbose_name_plural': 'Declaraciones Trimestrales',
                'ordering': ['-anio', '-trimestre'],
                'unique_together': {('socio', 'anio', 'trimestre')},
            },
        ),
    ]
